baseURL = "https://thecodesign.io"
languageCode = "en-us"
title = "The coDesign Publication"
defaultContentLanguage = "en"

#googleAnalytics = ""
#disqusShortname = ""

# hugo-xmin specific variables
theme = "thecodesigntheme"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

# enables ```lang ``` style syntax highlighted blocks
pygmentsCodeFences = true
pygmentsStyle = "murphy"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Posts"
    identifier = "posts"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Categories"
    identifier = "categories"
    url = "/categories/"
    weight = 2
[[menu.main]]
    name = "Tags"
    identifier = "tags"
    url = "/tags/"
    weight = 3

[[menu.main]]
    name = "About"
    identifier = "about"
    url = "/about/"
    weight = 4

[[menu.footer]]
  name = "Github"
  url = "https://github.com/coDesign"
  weight = 1

[[menu.footer]]
  name = "Twitter"
  url = "https://twitter.com/thecodesignpub"
  weight = 2

[[menu.footer]]
  name = "Telegram"
  url = "https://t.me/thecodesignpub"
  weight = 3


[author]
  name = "coDesign"

[params]
  keywords = "coDesign"
  rss = "/index.xml"
  telegram = "https://t.me/thecodesignpub"
  description = "Separating the signal from the noise."
  email = "thecodesignpub@gmail.com"
  github = "coDesign"
  twitter = "thecodesignpub"
  #twitterAnalytics = ""
